version: "3.8"

services:
  postgres:
    image: postgres:17.5
    container_name: delivery
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: delivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
